"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

interface LanguageContextType {
  language: string
  setLanguage: (lang: string) => void
  t: (key: string) => string
  getLanguageName: (code: string) => string
}

// List of available languages with their display names
export const availableLanguages = {
  en: "English",
  hi: "हिंदी",
  ta: "தமிழ்",
  ml: "മലയാളം",
  kn: "ಕನ್ನಡ",
  te: "తెలుగు"
}

const translations = {
  en: {
    // AI
    geminiOverloaded: "Gemini is overloaded. Retrying...",
    allKeysExceeded: "All available API keys have reached their quota limits. Please try again later.",
    aiWelcome: "🌾 Hello! I'm your AgriMithra AI assistant. I can help you with:\n\n• 📸 Image Analysis - Crop disease detection\n• 🎤 Voice Queries - Natural language farming questions\n• 🎥 Video Analysis - Field assessment and techniques\n• 📱 NFC Data - Smart tag information\n\nHow can I help you today?",
    // About
    aboutAgriMithraDesc: "Made for SIH 2025. By Students of SRM.",
    version: "Version", lastUpdated: "Last Updated", developer: "Developer",
    developerName: "SRM Students", by: "By", call: "Call", chatAction: "Chat",
    // Navigation
    dashboard: "Dashboard", marketplace: "Marketplace", profile: "Profile", chat: "AI Chat",
    // Dashboard
    welcome: "Welcome to AgriMithra",
    askQuestion: "Ask your farming question",
    voiceInput: "Voice Input", textQuery: "Text Query",
    photoAnalysis: "Photo Analysis", nfcScan: "NFC Scan",
    marketPrices: "Market Prices", govtSchemes: "Govt Schemes", diseaseAlerts: "Disease Alerts",
    askAgriMithra: "Ask AgriMithra",
    listeningSub: "I'm listening to your voice query now...",
    talkSub: "Speak naturally about your crops, pests, or market concerns",
    quickUpdates: "Quick Updates",
    liveLocation: "Live Location",
    latestSchemesNews: "Latest Schemes & News",
    viewAll: "View All",
    // Marketplace
    buy: "Buy", rent: "Rent", community: "Community",
    searchProducts: "Search products...", postNewItem: "Post New Item",
    // Profile
    settings: "Settings", notifications: "Notifications", logout: "Logout",
    languageSettings: "Select Language",
    changeAppLanguage: "Change the app display language",
    manageNotifications: "Manage alerts and updates",
    nfcManagement: "NFC & Offline",
    offlineAccessSettings: "Manage NFC and offline access",
    savedQueries: "Saved Queries",
    savedAnswers: "Saved Answers",
    support: "Support",
    getHelpContactUs: "Get help & contact us",
    aboutAgriMithra: "About AgriMithra",
    appInfoTeamDetails: "App info and team details",
    totalQueries: "Total Queries",
    cropsGrown: "Crops Grown",
    farm: "Farm",
    joined: "Joined",
    location_kochi: "Kochi, Kerala",
    acres: "Acres",
    rice: "Rice", coconut: "Coconut", pepper: "Pepper", cardamom: "Cardamom",
    unknown: "Unknown",
    // AI Chat
    listening: "Listening...", typing: "Typing...",
    askFarmingQuestion: "Ask your farming question...",
    // Community
    communityPosts: "Community Posts", shareExperience: "Share Experience",
    askCommunity: "Ask Community", farmingTips: "Farming Tips", discussions: "Discussions",
    // Auth
    verifyNumber: "Verify Your Number",
    enterPhoneToStart: "Enter your phone number to get started",
    sentCodeTo: "We sent a code to", phoneNumber: "Phone Number",
    enterPhone: "Enter your phone number", sending: "Sending...", sendOTP: "Send OTP",
    or: "OR", signingIn: "Signing in...", continueWithGoogle: "Continue with Google",
    enterOTP: "Enter OTP", enterOTPPlaceholder: "Enter 6-digit code",
    verifying: "Verifying...", verifyAndContinue: "Verify & Continue",
    changePhone: "Change Phone Number",
    termsAndPrivacy: "By continuing, you agree to our Terms of Service and Privacy Policy",
    // Onboarding
    onboarding_slide1_title: "Voice", onboarding_slide2_title: "Crop Price",
    onboarding_slide3_title: "Market Place",
    onboarding_slide1_desc: "Ask by voice, text, or image. Get instant answers to your farming questions.",
    onboarding_slide2_desc: "Get crop prices and government schemes. Access real-time market rates.",
    onboarding_slide3_desc: "Buy and sell in the farmers' marketplace. Connect with other farmers.",
    // Knowledge
    cropDiseaseAnalysis: "Crop disease analysis", currentMarketPrices: "Current market prices",
    weatherForecast: "Weather forecast", governmentSchemes: "Government schemes",
    fertilizerRecommendations: "Fertilizer recommendations", pestControlMethods: "Pest control methods",
    // Farmers Hub
    farmersHub: "Farmers Hub", market: "Market", fertilizers: "Fertilizers",
    pesticides: "Pesticides", guides: "Guides",
    knowledgeMarketGuides: "Knowledge · Market · Guides",
    apmc_notice: "APMC market prices. Prices vary by region.",
    allCategories: "All", cereals: "Cereals", pulses: "Pulses",
    vegetables: "Veggies", cashCrops: "Cash Crops",
    dosage: "Dosage", warning: "Warning", safetyInfo: "Safety Info",
  },
  hi: {
    geminiOverloaded: "Gemini सेवा व्यस्त है। पुनः प्रयास किया जा रहा है...",
    allKeysExceeded: "सभी उपलब्ध API कीज़ की कोटा सीमा समाप्त हो गई है। कृपया बाद में पुनः प्रयास करें।",
    aiWelcome: "🌾 नमस्ते! मैं आपका AgriMithra एआई सहायक हूँ। मैं आपकी मदद कर सकता हूँ:\n\n• 📸 चित्र विश्लेषण - फसल रोग पहचान\n• 🎤 वॉयस प्रश्न - प्राकृतिक भाषा में खेती के सवाल\n• 🎥 वीडियो विश्लेषण - खेत का मूल्यांकन\n• 📱 एनएफसी डेटा - स्मार्ट टैग जानकारी\n\nमैं आपकी किस प्रकार सहायता कर सकता हूँ?",
    aboutAgriMithraDesc: "SIH 2025 के लिए बनाया गया। SRM के छात्रों द्वारा।",
    version: "संस्करण", lastUpdated: "अंतिम अपडेट", developer: "डेवलपर",
    developerName: "SRM छात्र", by: "द्वारा", call: "कॉल", chatAction: "चैट",
    dashboard: "डैशबोर्ड", marketplace: "बाज़ार", profile: "प्रोफ़ाइल", chat: "AI चैट",
    welcome: "AgriMithra में आपका स्वागत है",
    askQuestion: "अपना कृषि प्रश्न पूछें",
    voiceInput: "आवाज़ इनपुट", textQuery: "टेक्स्ट प्रश्न",
    photoAnalysis: "फोटो विश्लेषण", nfcScan: "NFC स्कैन",
    marketPrices: "बाज़ार दर", govtSchemes: "सरकारी योजनाएं", diseaseAlerts: "रोग चेतावनी",
    askAgriMithra: "AgriMithra से पूछें",
    listeningSub: "मैं आपकी आवाज़ सुन रहा हूँ...",
    talkSub: "अपनी फसल, कीट या बाज़ार की चिंताओं के बारे में बोलें",
    quickUpdates: "त्वरित अपडेट",
    liveLocation: "लाइव स्थान",
    latestSchemesNews: "ताज़ा योजनाएं और समाचार",
    viewAll: "सभी देखें",
    buy: "खरीदें", rent: "किराया", community: "समुदाय",
    searchProducts: "उत्पाद खोजें...", postNewItem: "नया आइटम पोस्ट करें",
    settings: "सेटिंग्स", notifications: "सूचनाएं", logout: "लॉगआउट",
    languageSettings: "भाषा चुनें",
    changeAppLanguage: "ऐप की प्रदर्शन भाषा बदलें",
    manageNotifications: "अलर्ट और अपडेट प्रबंधित करें",
    nfcManagement: "NFC और ऑफलाइन",
    offlineAccessSettings: "NFC और ऑफलाइन एक्सेस प्रबंधित करें",
    savedQueries: "सहेजे गए प्रश्न",
    savedAnswers: "सहेजे गए उत्तर",
    support: "सहायता",
    getHelpContactUs: "सहायता प्राप्त करें और संपर्क करें",
    aboutAgriMithra: "AgriMithra के बारे में",
    appInfoTeamDetails: "ऐप जानकारी और टीम विवरण",
    totalQueries: "कुल प्रश्न",
    cropsGrown: "उगाई गई फसलें",
    farm: "खेत", joined: "शामिल हुए",
    location_kochi: "कोची, केरल",
    acres: "एकड़",
    rice: "चावल", coconut: "नारियल", pepper: "काली मिर्च", cardamom: "इलायची",
    unknown: "अज्ञात",
    listening: "सुन रहा है...", typing: "टाइप कर रहा है...",
    askFarmingQuestion: "अपना कृषि प्रश्न पूछें...",
    communityPosts: "समुदायिक पोस्ट", shareExperience: "अनुभव साझा करें",
    askCommunity: "समुदाय से पूछें", farmingTips: "कृषि सुझाव", discussions: "चर्चा",
    verifyNumber: "अपना नंबर सत्यापित करें",
    enterPhoneToStart: "शुरू करने के लिए अपना फ़ोन नंबर दर्ज करें",
    sentCodeTo: "हमने कोड भेजा है", phoneNumber: "फ़ोन नंबर",
    enterPhone: "अपना फ़ोन नंबर दर्ज करें", sending: "भेजा जा रहा है...", sendOTP: "OTP भेजें",
    or: "या", signingIn: "साइन इन हो रहा है...", continueWithGoogle: "Google से जारी रखें",
    enterOTP: "OTP दर्ज करें", enterOTPPlaceholder: "6-अंकों का कोड दर्ज करें",
    verifying: "सत्यापित हो रहा है...", verifyAndContinue: "सत्यापित करें और जारी रखें",
    changePhone: "फ़ोन नंबर बदलें",
    termsAndPrivacy: "जारी रखते हुए, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत हैं",
    onboarding_slide1_title: "आवाज़", onboarding_slide2_title: "फसल मूल्य",
    onboarding_slide3_title: "बाज़ार",
    onboarding_slide1_desc: "आवाज़, टेक्स्ट या छवि द्वारा पूछें। तुरंत उत्तर प्राप्त करें।",
    onboarding_slide2_desc: "फसल की कीमतें और सरकारी योजनाएं प्राप्त करें।",
    onboarding_slide3_desc: "किसान बाज़ार में खरीदें और बेचें।",
    cropDiseaseAnalysis: "फसल रोग विश्लेषण", currentMarketPrices: "वर्तमान बाजार मूल्य",
    weatherForecast: "मौसम पूर्वानुमान", governmentSchemes: "सरकारी योजनाएं",
    fertilizerRecommendations: "उर्वरक सिफारिशें", pestControlMethods: "कीट नियंत्रण विधियाँ",
    farmersHub: "किसान हब", market: "बाज़ार", fertilizers: "उर्वरक",
    pesticides: "कीटनाशक", guides: "गाइड",
    knowledgeMarketGuides: "ज्ञान · बाज़ार · गाइड",
    apmc_notice: "APMC बाज़ार मूल्य। कीमतें क्षेत्र के अनुसार भिन्न होती हैं।",
    allCategories: "सभी", cereals: "अनाज", pulses: "दालें",
    vegetables: "सब्ज़ियाँ", cashCrops: "नकदी फसलें",
    dosage: "खुराक", warning: "चेतावनी", safetyInfo: "सुरक्षा जानकारी",
  },
  ta: {
    geminiOverloaded: "Gemini அதிக பணி காரணமாக பதில் தர முடியவில்லை. மீண்டும் முயற்சிக்கிறது...",
    allKeysExceeded: "அனைத்து API விசைகளும் தங்கள் ஒதுக்கீடு வரம்பை அடைந்துவிட்டன. தயவுசெய்து பின்னர் முயற்சிக்கவும்.",
    aiWelcome: "🌾 வணக்கம்! நான் உங்கள் AgriMithra AI உதவியாளர். நான் உங்களுக்கு உதவ முடியும்:\n\n• 📸 படப் பகுப்பாய்வு - பயிர் நோய் கண்டறிதல்\n• 🎤 குரல் கேள்விகள் - விவசாய கேள்விகள்\n• 🎥 வீடியோ பகுப்பாய்வு - வயல் மதிப்பீடு\n• 📱 NFC தரவு - ஸ்மார்ட் டேக் தகவல்\n\nநான் எப்படி உதவலாம்?",
    aboutAgriMithraDesc: "SIH 2025-க்கு உருவாக்கப்பட்டது. SRM மாணவர்களால்.",
    version: "பதிப்பு", lastUpdated: "கடைசியாக புதுப்பிக்கப்பட்டது", developer: "டெவலப்பர்",
    developerName: "SRM மாணவர்கள்", by: "இவரால்", call: "அழை", chatAction: "அரட்டை",
    dashboard: "டாஷ்போர்டு", marketplace: "சந்தை", profile: "சுயவிவரம்", chat: "AI அரட்டை",
    welcome: "AgriMithra-க்கு வரவேற்கிறோம்",
    askQuestion: "உங்கள் விவசாய கேள்வியை கேளுங்கள்",
    voiceInput: "குரல் உள்ளீடு", textQuery: "உரை கேள்வி",
    photoAnalysis: "புகைப்பட பகுப்பாய்வு", nfcScan: "NFC ஸ்கேன்",
    marketPrices: "சந்தை விலைகள்", govtSchemes: "அரசு திட்டங்கள்", diseaseAlerts: "நோய் எச்சரிக்கை",
    askAgriMithra: "AgriMithra-ஐ கேளுங்கள்",
    listeningSub: "நான் இப்போது உங்கள் குரல் கேள்வியை கேட்கிறேன்...",
    talkSub: "உங்கள் பயிர், பூச்சி அல்லது சந்தை கவலைகளைப் பற்றி பேசுங்கள்",
    quickUpdates: "விரைவு புதுப்பிப்புகள்",
    liveLocation: "நேரடி இடம்",
    latestSchemesNews: "சமீபத்திய திட்டங்கள் மற்றும் செய்திகள்",
    viewAll: "அனைத்தையும் காண்க",
    buy: "வாங்க", rent: "வாடகை", community: "சமூகம்",
    searchProducts: "பொருட்களை தேடுங்கள்...", postNewItem: "புதிய பொருள் பதிவிடுங்கள்",
    settings: "அமைப்புகள்", notifications: "அறிவிப்புகள்", logout: "வெளியேறு",
    languageSettings: "மொழியை தேர்ந்தெடுக்கவும்",
    changeAppLanguage: "பயன்பாட்டு காட்சி மொழியை மாற்றவும்",
    manageNotifications: "விழிப்பூட்டல்கள் மற்றும் புதுப்பிப்புகளை நிர்வகிக்கவும்",
    nfcManagement: "NFC மற்றும் ஆஃப்லைன்",
    offlineAccessSettings: "NFC மற்றும் ஆஃப்லைன் அணுகலை நிர்வகிக்கவும்",
    savedQueries: "சேமிக்கப்பட்ட கேள்விகள்",
    savedAnswers: "சேமிக்கப்பட்ட பதில்கள்",
    support: "ஆதரவு",
    getHelpContactUs: "உதவி பெறவும் மற்றும் தொடர்பு கொள்ளவும்",
    aboutAgriMithra: "AgriMithra பற்றி",
    appInfoTeamDetails: "பயன்பாட்டு தகவல் மற்றும் குழு விவரங்கள்",
    totalQueries: "மொத்த கேள்விகள்",
    cropsGrown: "வளர்க்கப்பட்ட பயிர்கள்",
    farm: "பண்ணை", joined: "சேர்ந்தது",
    location_kochi: "கொச்சி, கேரளா",
    acres: "ஏக்கர்",
    rice: "அரிசி", coconut: "தேங்காய்", pepper: "மிளகு", cardamom: "ஏலக்காய்",
    unknown: "தெரியாத",
    listening: "கேட்கிறது...", typing: "தட்டுகிறது...",
    askFarmingQuestion: "உங்கள் விவசாய கேள்வியை கேளுங்கள்...",
    communityPosts: "சமூக பதிவுகள்", shareExperience: "அனுபவத்தை பகிரவும்",
    askCommunity: "சமூகத்திடம் கேளுங்கள்", farmingTips: "விவசாய குறிப்புகள்", discussions: "விவாதங்கள்",
    verifyNumber: "உங்கள் எண்ணை சரிபார்க்கவும்",
    enterPhoneToStart: "தொடங்க உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்",
    sentCodeTo: "நாங்கள் குறியீட்டை அனுப்பியுள்ளோம்", phoneNumber: "தொலைபேசி எண்",
    enterPhone: "உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்", sending: "அனுப்புகிறது...", sendOTP: "OTP அனுப்பவும்",
    or: "அல்லது", signingIn: "உள்நுழைகிறது...", continueWithGoogle: "Google மூலம் தொடரவும்",
    enterOTP: "OTP உள்ளிடவும்", enterOTPPlaceholder: "6-எண் குறியீட்டை உள்ளிடவும்",
    verifying: "சரிபார்க்கிறது...", verifyAndContinue: "சரிபார்த்து தொடரவும்",
    changePhone: "தொலைபேசி எண்ணை மாற்றவும்",
    termsAndPrivacy: "தொடர்வதன் மூலம், எங்கள் சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஒப்புக்கொள்கிறீர்கள்",
    onboarding_slide1_title: "குரல்", onboarding_slide2_title: "பயிர் விலை",
    onboarding_slide3_title: "சந்தை",
    onboarding_slide1_desc: "குரல், உரை அல்லது படம் மூலம் கேளுங்கள். உடனடி பதில்கள் பெறுங்கள்.",
    onboarding_slide2_desc: "பயிர் விலைகள் மற்றும் அரசு திட்டங்களைப் பெறுங்கள்.",
    onboarding_slide3_desc: "விவசாயிகள் சந்தையில் வாங்கி விற்கவும்.",
    cropDiseaseAnalysis: "பயிர் நோய் பகுப்பாய்வு", currentMarketPrices: "தற்போதைய சந்தை விலைகள்",
    weatherForecast: "வானிலை முன்னறிவு", governmentSchemes: "அரசு திட்டங்கள்",
    fertilizerRecommendations: "உர பரிந்துரைகள்", pestControlMethods: "பூச்சி கட்டுப்பாட்டு முறைகள்",
    farmersHub: "விவசாயி மையம்", market: "சந்தை", fertilizers: "உரங்கள்",
    pesticides: "பூச்சிக்கொல்லிகள்", guides: "வழிகாட்டிகள்",
    knowledgeMarketGuides: "அறிவு · சந்தை · வழிகாட்டிகள்",
    apmc_notice: "APMC சந்தை விலைகள். பகுதிக்கு ஏற்ப விலைகள் மாறும்.",
    allCategories: "அனைத்தும்", cereals: "தானியங்கள்", pulses: "பருப்பு வகைகள்",
    vegetables: "காய்கறிகள்", cashCrops: "பண பயிர்கள்",
    dosage: "அளவு", warning: "எச்சரிக்கை", safetyInfo: "பாதுகாப்பு தகவல்",
  },
  ml: {
    geminiOverloaded: "Gemini ഓവർലോഡ് ആണ്. വീണ്ടും ശ്രമിക്കുന്നു...",
    allKeysExceeded: "എല്ലാ ലഭ്യമായ API കീകളും അവയുടെ ക്വോട്ട പരിധി കഴിഞ്ഞിരിക്കുന്നു. ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക.",
    aiWelcome: "🌾 നമസ്കാരം! ഞാൻ നിങ്ങളുടെ AgriMithra AI സഹായി. ഞാൻ നിങ്ങളെ സഹായിക്കാൻ കഴിയും:\n\n• 📸 ചിത്ര വിശകലനം - വിള രോഗ നിർണയം\n• 🎤 ശബ്ദ ചോദ്യങ്ങൾ - കൃഷി ചോദ്യങ്ങൾ\n• 🎥 വീഡിയോ വിശകലനം - വയൽ മൂല്യനിർണയം\n• 📱 NFC ഡാറ്റ - സ്മാർട്ട് ടാഗ് വിവരം\n\nഞാൻ എങ്ങനെ സഹായിക്കാം?",
    aboutAgriMithraDesc: "SIH 2025-ന് വേണ്ടി നിർമ്മിച്ചത്. SRM വിദ്യാർത്ഥികൾ നിർമ്മിച്ചത്.",
    version: "പതിപ്പ്", lastUpdated: "അവസാനമായി പുതുക്കിയത്", developer: "ഡെവലപ്പർ",
    developerName: "SRM വിദ്യാർത്ഥികൾ", by: "വഴി", call: "വിളിക്കുക", chatAction: "ചാറ്റ്",
    dashboard: "ഡാഷ്ബോർഡ്", marketplace: "ചന്ത", profile: "പ്രൊഫൈൽ", chat: "AI ചാറ്റ്",
    welcome: "AgriMithra-യിലേക്ക് സ്വാഗതം",
    askQuestion: "നിങ്ങളുടെ കൃഷി ചോദ്യങ്ങൾ ചോദിക്കുക",
    voiceInput: "ശബ്ദ ഇൻപുട്ട്", textQuery: "ടെക്സ്റ്റ് ചോദ്യം",
    photoAnalysis: "ഫോട്ടോ വിശകലനം", nfcScan: "NFC സ്കാൻ",
    marketPrices: "ചന്ത വിലകൾ", govtSchemes: "സർക്കാർ പദ്ധതികൾ", diseaseAlerts: "രോഗ മുന്നറിയിപ്പ്",
    askAgriMithra: "AgriMithra-നോട് ചോദിക്കുക",
    listeningSub: "ഞാൻ ഇപ്പോൾ നിങ്ങളുടെ ശബ്ദ ചോദ്യം കേൾക്കുന്നു...",
    talkSub: "നിങ്ങളുടെ വിളകൾ, കീടങ്ങൾ അല്ലെങ്കിൽ വിപണി ആശങ്കകളെക്കുറിച്ച് സ്വാഭാവികമായി സംസാരിക്കുക",
    quickUpdates: "ദ്രുത അപ്‌ഡേറ്റുകൾ",
    liveLocation: "തത്സമയ സ്ഥാനം",
    latestSchemesNews: "ഏറ്റവും പുതിയ പദ്ധതികളും വാർത്തകളും",
    viewAll: "എല്ലാം കാണുക",
    buy: "വാങ്ങുക", rent: "വാടക", community: "സമൂഹം",
    searchProducts: "ഉൽപ്പന്നങ്ങൾ തിരയുക...", postNewItem: "പുതിയ ഉൽപ്പന്നം പോസ്റ്റ് ചെയ്യുക",
    settings: "ക്രമീകരണങ്ങൾ", notifications: "അറിയിപ്പുകൾ", logout: "ലോഗ്ഔട്ട്",
    languageSettings: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    changeAppLanguage: "ആപ്പ് ഡിസ്പ്ലേ ഭാഷ മാറ്റുക",
    manageNotifications: "അലർട്ടുകളും അപ്‌ഡേറ്റുകളും നിയന്ത്രിക്കുക",
    nfcManagement: "NFC & ഓഫ്‌ലൈൻ",
    offlineAccessSettings: "NFC, ഓഫ്‌ലൈൻ ആക്സസ് നിയന്ത്രിക്കുക",
    savedQueries: "സംരക്ഷിച്ച ചോദ്യങ്ങൾ",
    savedAnswers: "സംരക്ഷിച്ച ഉത്തരങ്ങൾ",
    support: "പിന്തുണ",
    getHelpContactUs: "സഹായം നേടുക & ഞങ്ങളെ ബന്ധപ്പെടുക",
    aboutAgriMithra: "AgriMithra-യെ കുറിച്ച്",
    appInfoTeamDetails: "ആപ്പ് വിവരവും ടീം വിശദാംശങ്ങളും",
    totalQueries: "ആകെ ചോദ്യങ്ങൾ",
    cropsGrown: "കൃഷി ചെയ്ത വിളകൾ",
    farm: "ഫാം", joined: "ചേർന്നത്",
    location_kochi: "കൊച്ചി, കേരളം",
    acres: "ഏക്കർ",
    rice: "നെല്ല്", coconut: "തേങ്ങ", pepper: "കുരുമുളക്", cardamom: "ഏലം",
    unknown: "അജ്ഞാതം",
    listening: "കേൾക്കുന്നു...", typing: "ടൈപ്പ് ചെയ്യുന്നു...",
    askFarmingQuestion: "നിങ്ങളുടെ കൃഷി ചോദ്യങ്ങൾ ചോദിക്കുക...",
    communityPosts: "സമൂഹ പോസ്റ്റുകൾ", shareExperience: "അനുഭവം പങ്കിടുക",
    askCommunity: "സമൂഹത്തോട് ചോദിക്കുക", farmingTips: "കൃഷി ടിപ്പുകൾ", discussions: "ചർച്ചകൾ",
    verifyNumber: "നിങ്ങളുടെ നമ്പർ സ്ഥിരീകരിക്കുക",
    enterPhoneToStart: "തുടങ്ങാൻ നിങ്ങളുടെ ഫോൺ നമ്പർ നൽകുക",
    sentCodeTo: "നാം കോഡ് അയച്ചിട്ടുണ്ട്", phoneNumber: "ഫോൺ നമ്പർ",
    enterPhone: "നിങ്ങളുടെ ഫോൺ നമ്പർ നൽകുക", sending: "അയയ്ക്കുന്നു...", sendOTP: "OTP അയയ്ക്കുക",
    or: "അല്ലെങ്കിൽ", signingIn: "സൈൻ ഇൻ ചെയ്യുന്നു...", continueWithGoogle: "Google ഉപയോഗിച്ച് തുടരുക",
    enterOTP: "OTP നൽകുക", enterOTPPlaceholder: "6-അങ്കം കോഡ് നൽകുക",
    verifying: "സ്ഥിരീകരിക്കുന്നു...", verifyAndContinue: "സ്ഥിരീകരിച്ച് തുടരുക",
    changePhone: "ഫോൺ നമ്പർ മാറ്റുക",
    termsAndPrivacy: "തുടരുമ്പോൾ, നിങ്ങൾ ഞങ്ങളുടെ സേവന നിബന്ധനകളും സ്വകാര്യതാ നയവും അംഗീകരിക്കുന്നു",
    onboarding_slide1_title: "ശബ്ദം", onboarding_slide2_title: "വിള വില",
    onboarding_slide3_title: "ചന്ത",
    onboarding_slide1_desc: "ശബ്ദം, ടെക്സ്റ്റ് അല്ലെങ്കിൽ ചിത്രം വഴി ചോദിക്കുക. ഉടൻ ഉത്തരങ്ങൾ നേടുക.",
    onboarding_slide2_desc: "വിള വിലകളും സർക്കാർ പദ്ധതികളും നേടുക.",
    onboarding_slide3_desc: "കർഷകരുടെ ചന്തയിൽ വാങ്ങി വിൽക്കുക.",
    cropDiseaseAnalysis: "വള രോഗ വിശകലനം", currentMarketPrices: "നിലവിലെ മാർക്കറ്റ് വിലകൾ",
    weatherForecast: "വാതാവര പ്രവചനം", governmentSchemes: "സർക്കാർ പദ്ധതികൾ",
    fertilizerRecommendations: "വള ശുപാർശകൾ", pestControlMethods: "കീട നിയന്ത്രണ രീതികൾ",
    farmersHub: "കർഷക ഹബ്", market: "ചന്ത", fertilizers: "വളങ്ങൾ",
    pesticides: "കീടനാശിനികൾ", guides: "ഗൈഡുകൾ",
    knowledgeMarketGuides: "അറിവ് · ചന്ത · ഗൈഡുകൾ",
    apmc_notice: "APMC ചന്ത വിലകൾ. വിലകൾ പ്രദേശം അനുസരിച്ച് മാറും.",
    allCategories: "എല്ലാം", cereals: "ധാന്യങ്ങൾ", pulses: "പയർ വർഗ്ഗങ്ങൾ",
    vegetables: "പച്ചക്കറികൾ", cashCrops: "നണ്ണ്യ വിളകൾ",
    dosage: "ഡോസ്", warning: "മുന്നറിയിപ്പ്", safetyInfo: "സുരക്ഷാ വിവരം",
  },
  kn: {
    geminiOverloaded: "Gemini ಓವರ್‌ಲೋಡ್ ಆಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸುತ್ತಿದೆ...",
    allKeysExceeded: "ಎಲ್ಲಾ ಲಭ್ಯವಿರುವ API ಕೀಗಳು ಅವುಗಳ ಕೋಟಾ ಮಿತಿಯನ್ನು ತಲುಪಿವೆ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    aiWelcome: "🌾 ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ AgriMithra AI ಸಹಾಯಕ. ನಾನು ನಿಮಗೆ ಸಹಾಯ ಮಾಡಬಹುದು:\n\n• 📸 ಚಿತ್ರ ವಿಶ್ಲೇಷಣೆ - ಬೆಳೆ ರೋಗ ಪತ್ತೆ\n• 🎤 ಧ್ವನಿ ಪ್ರಶ್ನೆಗಳು - ಕೃಷಿ ಪ್ರಶ್ನೆಗಳು\n• 🎥 ವೀಡಿಯೊ ವಿಶ್ಲೇಷಣೆ - ಹೊಲ ಮೌಲ್ಯಮಾಪನ\n• 📱 NFC ಡೇಟಾ - ಸ್ಮಾರ್ಟ್ ಟ್ಯಾಗ್ ಮಾಹಿತಿ\n\nನಾನು ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
    aboutAgriMithraDesc: "SIH 2025 ಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ. SRM ವಿದ್ಯಾರ್ಥಿಗಳಿಂದ.",
    version: "ಆವೃತ್ತಿ", lastUpdated: "ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ", developer: "ಡೆವಲಪರ್",
    developerName: "SRM ವಿದ್ಯಾರ್ಥಿಗಳು", by: "ಮೂಲಕ", call: "ಕರೆ", chatAction: "ಚಾಟ್",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", marketplace: "ಮಾರುಕಟ್ಟೆ", profile: "ಪ್ರೊಫೈಲ್", chat: "AI ಚಾಟ್",
    welcome: "AgriMithra ಗೆ ಸ್ವಾಗತ",
    askQuestion: "ನಿಮ್ಮ ಕೃಷಿ ಪ್ರಶ್ನೆ ಕೇಳಿ",
    voiceInput: "ಧ್ವನಿ ಇನ್‌ಪುಟ್", textQuery: "ಪಠ್ಯ ಪ್ರಶ್ನೆ",
    photoAnalysis: "ಫೋಟೋ ವಿಶ್ಲೇಷಣೆ", nfcScan: "NFC ಸ್ಕ್ಯಾನ್",
    marketPrices: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು", govtSchemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು", diseaseAlerts: "ರೋಗ ಎಚ್ಚರಿಕೆಗಳು",
    askAgriMithra: "AgriMithra ಅನ್ನು ಕೇಳಿ",
    listeningSub: "ನಾನು ಈಗ ನಿಮ್ಮ ಧ್ವನಿ ಪ್ರಶ್ನೆ ಕೇಳುತ್ತಿದ್ದೇನೆ...",
    talkSub: "ನಿಮ್ಮ ಬೆಳೆಗಳು, ಕೀಟಗಳು ಅಥವಾ ಮಾರುಕಟ್ಟೆ ಕಾಳಜಿಗಳ ಬಗ್ಗೆ ಸ್ವಾಭಾವಿಕವಾಗಿ ಮಾತನಾಡಿ",
    quickUpdates: "ತ್ವರಿತ ಅಪ್‌ಡೇಟ್‌ಗಳು",
    liveLocation: "ನೇರ ಸ್ಥಳ",
    latestSchemesNews: "ಇತ್ತೀಚಿನ ಯೋಜನೆಗಳು ಮತ್ತು ಸುದ್ದಿಗಳು",
    viewAll: "ಎಲ್ಲವನ್ನೂ ತೋರಿಸಿ",
    buy: "ಖರೀದಿಸಿ", rent: "ಬಾಡಿಗೆ", community: "ಸಮುದಾಯ",
    searchProducts: "ಉತ್ಪಾದನೆಗಳನ್ನು ಹುಡುಕಿ...", postNewItem: "ಹೊಸ ಐಟಂ ಪೋಸ್ಟ್ ಮಾಡಿ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", notifications: "ಅಧಿಸೂಚನೆಗಳು", logout: "ಲಾಗ್‌ಔಟ್",
    languageSettings: "ಭಾಷಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    changeAppLanguage: "ಅಪ್ಲಿಕೇಶನ್ ಪ್ರದರ್ಶನ ಭಾಷೆ ಬದಲಿಸಿ",
    manageNotifications: "ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    nfcManagement: "NFC & ಆಫ್‌ಲೈನ್",
    offlineAccessSettings: "NFC ಮತ್ತು ಆಫ್‌ಲೈನ್ ಪ್ರವೇಶ ನಿರ್ವಹಿಸಿ",
    savedQueries: "ಉಳಿಸಿದ ಪ್ರಶ್ನೆಗಳು",
    savedAnswers: "ಉಳಿಸಿದ ಉತ್ತರಗಳು",
    support: "ಬೆಂಬಲ",
    getHelpContactUs: "ಸಹಾಯ ಪಡೆಯಿರಿ ಮತ್ತು ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
    aboutAgriMithra: "AgriMithra ಬಗ್ಗೆ",
    appInfoTeamDetails: "ಅಪ್ಲಿಕೇಶನ್ ಮಾಹಿತಿ ಮತ್ತು ತಂಡ ವಿವರಗಳು",
    totalQueries: "ಒಟ್ಟು ಪ್ರಶ್ನೆಗಳು",
    cropsGrown: "ಬೆಳೆದ ಬೆಳೆಗಳು",
    farm: "ಹೊಲ", joined: "ಸೇರಿದ",
    location_kochi: "ಕೊಚ್ಚಿ, ಕೇರಳ",
    acres: "ಎಕರೆ",
    rice: "ಅಕ್ಕಿ", coconut: "ತೆಂಗಿನಕಾಯಿ", pepper: "ಕಾಳು ಮೆಣಸು", cardamom: "ಏಲಕ್ಕಿ",
    unknown: "ತಿಳಿದಿಲ್ಲ",
    listening: "ಕೇಳುತ್ತಿದೆ...", typing: "ಟೈಪ್ ಮಾಡುತ್ತಿದೆ...",
    askFarmingQuestion: "ನಿಮ್ಮ ಕೃಷಿ ಪ್ರಶ್ನೆ ಕೇಳಿ...",
    communityPosts: "ಸಮುದಾಯ ಪೋಸ್ಟ್‌ಗಳು", shareExperience: "ಅನುಭವ ಹಂಚಿಕೊಳ್ಳಿ",
    askCommunity: "ಸಮುದಾಯವನ್ನು ಕೇಳಿ", farmingTips: "ಕೃಷಿ ಸಲಹೆಗಳು", discussions: "ಚರ್ಚೆಗಳು",
    verifyNumber: "ನಿಮ್ಮ ಸಂಖ್ಯೆಯನ್ನು ಪರಿಶೀಲಿಸಿ",
    enterPhoneToStart: "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    sentCodeTo: "ನಾವು ಕೋಡ್ ಕಳುಹಿಸಿದ್ದೇವೆ", phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
    enterPhone: "ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ", sending: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...", sendOTP: "OTP ಕಳುಹಿಸಿ",
    or: "ಅಥವಾ", signingIn: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...", continueWithGoogle: "Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ",
    enterOTP: "OTP ನಮೂದಿಸಿ", enterOTPPlaceholder: "6-ಅಂಕಿ ಕೋಡ್ ನಮೂದಿಸಿ",
    verifying: "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...", verifyAndContinue: "ಪರಿಶೀಲಿಸಿ ಮುಂದುವರಿಯಿರಿ",
    changePhone: "ಫೋನ್ ಸಂಖ್ಯೆ ಬದಲಿಸಿ",
    termsAndPrivacy: "ಮುಂದುವರಿಯುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ ಸೇವಾ ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿಗೆ ಸಮ್ಮತಿಸುತ್ತೀರಿ",
    onboarding_slide1_title: "ಧ್ವನಿ", onboarding_slide2_title: "ಬೆಳೆ ಬೆಲೆ",
    onboarding_slide3_title: "ಮಾರುಕಟ್ಟೆ",
    onboarding_slide1_desc: "ಧ್ವನಿ, ಪಠ್ಯ ಅಥವಾ ಚಿತ್ರದ ಮೂಲಕ ಕೇಳಿ. ತಕ್ಷಣ ಉತ್ತರ ಪಡೆಯಿರಿ.",
    onboarding_slide2_desc: "ಬೆಳೆ ಬೆಲೆಗಳು ಮತ್ತು ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಪಡೆಯಿರಿ.",
    onboarding_slide3_desc: "ರೈತರ ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಖರೀದಿಸಿ ಮಾರಿ.",
    cropDiseaseAnalysis: "ಬೆಳೆ ರೋಗ ವಿಶ್ಲೇಷಣೆ", currentMarketPrices: "ಪ್ರಸ್ತುತ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು",
    weatherForecast: "ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ", governmentSchemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    fertilizerRecommendations: "ಗೊಬ್ಬರ ಶಿಫಾರಸುಗಳು", pestControlMethods: "ಕೀಟ ನಿಯಂತ್ರಣ ವಿಧಾನಗಳು",
    farmersHub: "ರೈತ ಹಬ್", market: "ಮಾರುಕಟ್ಟೆ", fertilizers: "ಗೊಬ್ಬರಗಳು",
    pesticides: "ಕೀಟನಾಶಕಗಳು", guides: "ಮಾರ್ಗದರ್ಶಿಗಳು",
    knowledgeMarketGuides: "ಜ್ಞಾನ · ಮಾರುಕಟ್ಟೆ · ಮಾರ್ಗದರ್ಶಿಗಳು",
    apmc_notice: "APMC ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು. ಬೆಲೆಗಳು ಪ್ರದೇಶಕ್ಕೆ ಅನುಸಾರ ಬದಲಾಗುತ್ತವೆ.",
    allCategories: "ಎಲ್ಲವೂ", cereals: "ಧಾನ್ಯಗಳು", pulses: "ದ್ವಿದಳ ಧಾನ್ಯಗಳು",
    vegetables: "ತರಕಾರಿಗಳು", cashCrops: "ವಾಣಿಜ್ಯ ಬೆಳೆಗಳು",
    dosage: "ಪ್ರಮಾಣ", warning: "ಎಚ್ಚರಿಕೆ", safetyInfo: "ಸುರಕ್ಷತಾ ಮಾಹಿತಿ",
  },
  te: {
    geminiOverloaded: "Gemini ఓవర్‌లోడ్ అయ్యింది. మళ్లీ ప్రయత్నిస్తోంది...",
    allKeysExceeded: "అందుబాటులో ఉన్న అన్ని API కీలు వాటి కోటా పరిమితులను చేరుకున్నాయి. దయచేసి తర్వాత మళ్ళీ ప్రయత్నించండి.",
    aiWelcome: "🌾 నమస్కారం! నేను మీ AgriMithra AI సహాయకుడిని. నేను మీకు సహాయం చేయగలను:\n\n• 📸 చిత్ర విశ్లేషణ - పంట వ్యాధి గుర్తింపు\n• 🎤 వాయిస్ ప్రశ్నలు - వ్యవసాయ ప్రశ్నలు\n• 🎥 వీడియో విశ్లేషణ - పొలం అంచనా\n• 📱 NFC డేటా - స్మార్ట్ ట్యాగ్ సమాచారం\n\nనేను మీకు ఎలా సహాయపడగలను?",
    aboutAgriMithraDesc: "SIH 2025 కోసం తయారు చేయబడింది. SRM విద్యార్థుల ద్వారా.",
    version: "వెర్షన్", lastUpdated: "చివరిగా నవీకరించబడింది", developer: "డెవలపర్",
    developerName: "SRM విద్యార్థులు", by: "ద్వారా", call: "కాల్", chatAction: "చాట్",
    dashboard: "డ్యాష్‌బోర్డ్", marketplace: "మార్కెట్‌ప్లేస్", profile: "ప్రొఫైల్", chat: "AI చాట్",
    welcome: "AgriMithra కి స్వాగతం",
    askQuestion: "మీ వ్యవసాయ ప్రశ్నను అడగండి",
    voiceInput: "వాయిస్ ఇన్‌పుట్", textQuery: "టెక్స్ట్ ప్రశ్న",
    photoAnalysis: "ఫోటో విశ్లేషణ", nfcScan: "NFC స్కాన్",
    marketPrices: "మార్కెట్ ధరలు", govtSchemes: "ప్రభుత్వ పథకాలు", diseaseAlerts: "వ్యాధి హెచ్చరికలు",
    askAgriMithra: "AgriMithra ని అడగండి",
    listeningSub: "నేను ఇప్పుడు మీ వాయిస్ ప్రశ్నను వింటున్నాను...",
    talkSub: "మీ పంటలు, పురుగులు లేదా మార్కెట్ సమస్యల గురించి సహజంగా మాట్లాడండి",
    quickUpdates: "త్వరిత అప్‌డేట్‌లు",
    liveLocation: "లైవ్ లొకేషన్",
    latestSchemesNews: "తాజా పథకాలు మరియు వార్తలు",
    viewAll: "అన్నీ చూడండి",
    buy: "కొనండి", rent: "అద్దెకు", community: "కమ్యూనిటీ",
    searchProducts: "ఉత్పత్తులను శోధించండి...", postNewItem: "కొత్త వస్తువును పోస్ట్ చేయండి",
    settings: "సెట్టింగ్‌లు", notifications: "నోటిఫికేషన్లు", logout: "లాగ్ అవుట్",
    languageSettings: "భాష ఎంపిక",
    changeAppLanguage: "యాప్ ప్రదర్శన భాషను మార్చండి",
    manageNotifications: "హెచ్చరికలు మరియు నవీకరణలను నిర్వహించండి",
    nfcManagement: "NFC & ఆఫ్‌లైన్",
    offlineAccessSettings: "NFC మరియు ఆఫ్‌లైన్ యాక్సెస్ నిర్వహించండి",
    savedQueries: "సేవ్ చేసిన ప్రశ్నలు",
    savedAnswers: "సేవ్ చేసిన సమాధానాలు",
    support: "మద్దతు",
    getHelpContactUs: "సహాయం పొందండి & మాతో సంప్రదించండి",
    aboutAgriMithra: "AgriMithra గురించి",
    appInfoTeamDetails: "యాప్ సమాచారం మరియు జట్టు వివరాలు",
    totalQueries: "మొత్తం ప్రశ్నలు",
    cropsGrown: "పెంచిన పంటలు",
    farm: "పొలం", joined: "చేరారు",
    location_kochi: "కొచ్చి, కేరళ",
    acres: "ఎకరాలు",
    rice: "వరి", coconut: "కొబ్బరి", pepper: "మిరియాలు", cardamom: "యాలకులు",
    unknown: "తెలియదు",
    listening: "వింటున్నాను...", typing: "టైప్ చేస్తున్నాను...",
    askFarmingQuestion: "మీ వ్యవసాయ ప్రశ్నను అడగండి...",
    communityPosts: "కమ్యూనిటీ పోస్ట్‌లు", shareExperience: "అనుభవాన్ని పంచుకోండి",
    askCommunity: "కమ్యూనిటీని అడగండి", farmingTips: "వ్యవసాయ చిట్కాలు", discussions: "చర్చలు",
    verifyNumber: "మీ నంబర్‌ను ధృవీకరించండి",
    enterPhoneToStart: "ప్రారంభించడానికి మీ ఫోన్ నంబర్‌ను నమోదు చేయండి",
    sentCodeTo: "మేము కోడ్‌ని పంపాము", phoneNumber: "ఫోన్ నంబర్",
    enterPhone: "మీ ఫోన్ నంబర్‌ను నమోదు చేయండి", sending: "పంపుతోంది...", sendOTP: "OTP పంపండి",
    or: "లేదా", signingIn: "సైన్ ఇన్ అవుతోంది...", continueWithGoogle: "Google తో కొనసాగించండి",
    enterOTP: "OTP నమోదు చేయండి", enterOTPPlaceholder: "6-అంకెల కోడ్‌ని నమోదు చేయండి",
    verifying: "ధృవీకరిస్తోంది...", verifyAndContinue: "ధృవీకరించి కొనసాగించండి",
    changePhone: "ఫోన్ నంబర్‌ను మార్చండి",
    termsAndPrivacy: "కొనసాగడం ద్వారా, మీరు మా సేవా నిబంధనలు మరియు గోపినియతా విధానానికి అంగీకరిస్తున్నారు",
    onboarding_slide1_title: "వాయిస్", onboarding_slide2_title: "పంట ధర",
    onboarding_slide3_title: "మార్కెట్",
    onboarding_slide1_desc: "వాయిస్, టెక్స్ట్ లేదా చిత్రం ద్వారా అడగండి. తక్షణ సమాధానాలు పొందండి.",
    onboarding_slide2_desc: "పంట ధరలు మరియు ప్రభుత్వ పథకాలు పొందండి.",
    onboarding_slide3_desc: "రైతుల మార్కెట్‌లో కొని అమ్మండి.",
    cropDiseaseAnalysis: "పంట వ్యాధి విశ్లేషణ", currentMarketPrices: "ప్రస్తుత మార్కెట్ ధరలు",
    weatherForecast: "వాతావరణ సూచన", governmentSchemes: "ప్రభుత్వ పథకాలు",
    fertilizerRecommendations: "ఎరువుల సిఫార్సులు", pestControlMethods: "పురుగుమందుల నియంత్రణ పద్ధతులు",
    farmersHub: "రైతు హబ్", market: "మార్కెట్", fertilizers: "ఎరువులు",
    pesticides: "పురుగుమందులు", guides: "గైడ్‌లు",
    knowledgeMarketGuides: "జ్ఞానం · మార్కెట్ · గైడ్‌లు",
    apmc_notice: "APMC మార్కెట్ ధరలు. ధరలు ప్రాంతాన్ని బట్టి మారుతాయి.",
    allCategories: "అన్నీ", cereals: "తృణధాన్యాలు", pulses: "పప్పు ధాన్యాలు",
    vegetables: "కూరగాయలు", cashCrops: "వాణిజ్య పంటలు",
    dosage: "మోతాదు", warning: "హెచ్చరిక", safetyInfo: "భద్రతా సమాచారం",
  },

}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("agrimithra-language")
    if (savedLanguage && savedLanguage in translations) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: string) => {
    setLanguage(lang)
    localStorage.setItem("agrimithra-language", lang)
  }

  const t = (key: string): string => {
    const translation = translations[language as keyof typeof translations]
    return translation?.[key as keyof typeof translation] || key
  }

  const getLanguageName = (code: string): string => {
    return availableLanguages[code as keyof typeof availableLanguages] || code
  }

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage: handleSetLanguage, 
      t,
      getLanguageName
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
